/**
 * Browser and Node globals the site actually uses. Listed explicitly rather
 * than pulling in the `globals` package for one object.
 */
export default {
  document: 'readonly',
  window: 'readonly',
  navigator: 'readonly',
  console: 'readonly',
  performance: 'readonly',
  localStorage: 'readonly',
  matchMedia: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  IntersectionObserver: 'readonly',
  PerformanceObserver: 'readonly',
  PerformanceEntry: 'readonly',
  PerformanceObserverEntryList: 'readonly',
  PerformanceObserverInit: 'readonly',
  PerformanceNavigationTiming: 'readonly',
  PerformanceResourceTiming: 'readonly',
  ResizeObserver: 'readonly',
  HTMLElement: 'readonly',
  HTMLInputElement: 'readonly',
  HTMLButtonElement: 'readonly',
  HTMLHeadingElement: 'readonly',
  KeyboardEvent: 'readonly',
  SubmitEvent: 'readonly',
  Event: 'readonly',
  CustomEvent: 'readonly',
  history: 'readonly',
  location: 'readonly',
  fetch: 'readonly',
  Response: 'readonly',
  Request: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  FormData: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
  globalThis: 'readonly',
  process: 'readonly',
  Blob: 'readonly',
  Intl: 'readonly',
};
